### ISSUE TITLE
Use dev branch

### ISSUE THREAD

**Issue by YiNNx** [kkkstra/byitter#6]
For commits under development, you should use `dev` branch. 😉

**Comment by kkkstra** [comment]
In fact, I used branches like `refactor/jwt`, and merged them into `master` branch.

**Comment by YiNNx** [comment]
Usually, the `master` branch is for the fully-tested and well-featured production code... We should use branches to differentiate the development code and production code.

**Comment by kkkstra** [comment]
> Usually, the `master` branch is for the fully-tested and well-featured production code... We should use branch to differentiate the development code and production code.

Understood. Thx. :)
