### ISSUE TITLE
Change JWT claim of the user identity

### ISSUE THREAD

**Issue by YiNNx** [kkkstra/byitter#7]
https://github.com/kkkstra/NGB/blob/2a25b127e0ac12f57d2befe7abe4bcd98f594115/pkg/util/jwt.go#L23-L28

In `jwt.StandardClaims`, `id` refers to `jti` (JWT ID),  which is a unique identifier **for a jwt** that can be used to prevent the JWT from being replayed.

For user identity, you shoud use `jwt.StandardClaims.Sub`, the subject of the JWT (the user).

More info can be found in https://www.rfc-editor.org/rfc/rfc7519#section-4.1

---

Btw, you can fill more claims of `jwt.StandardClaims` on the basis of https://www.rfc-editor.org/rfc/rfc7519#section-4.1. It doesn't matter but it's fun to do so :D

**Comment by kkkstra** [comment]
Fixed.

**Comment by YiNNx** [comment]
Please make seperate PR to fix the issue, and the PR should be checked before closing the issue🥺
