### ISSUE TITLE
API Design is not enough RESTful

### ISSUE THREAD

**Issue by YiNNx** [kkkstra/byitter#9]
https://github.com/kkkstra/NGB/blob/f8ca797b70cbacf8bb1ae71b062a0025656a38fc/internal/router/user.go#L10-L25

**Comment by YiNNx** [comment]
For 

```go
r.POST("/signup", controller.SignUp) 
r.POST("/signin", controller.SignIn) 
``` 
View https://stackoverflow.com/questions/7140074/restfully-design-login-or-register-resources

**Comment by YiNNx** [comment]
Why `GetUserProfile` and `EditUserProfile` use different routers? It seems quite strange.

**Comment by kkkstra** [comment]
Fixed.
